object Versions {
    const val kotlin = "1.6.0"
    const val coroutines = "1.6.0"
    const val gradle = "7.0.4"
    const val appcompat = "1.2.0"
    const val constraintLayout = "2.0.4"
    const val material = "1.2.1"
    const val hilt = "2.38.1"
    const val hiltPlugin = "2.38.1"
    const val hiltAndroidX = "1.0.0-alpha02"
    const val glide = "4.11.0"
    const val lifecycle = "2.4.0"
    const val fragmentKtx = "1.2.5"
    const val junit = "4.12"
    const val mockito = "3.8.0"
    const val mockitoNhaarmanKotlin = "2.2.0"
    const val mockitoKotlin = "4.0.0"
    const val mockitoInline = "4.2.0"
    const val archCoreTesting = "2.0.0"
    const val assertj = "3.14.0"
    const val navVersion = "2.3.5"
    const val dataBinding = "3.1.4"
    const val retrofit = "2.9.0"
    const val okHttp = "4.9.0"
    const val gson = "2.8.6"
    const val androidSupport = "1.0.0"
}
